version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - Romitou
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.11.0
    - 3.9.1
  - dependency-name: mongoose
    versions:
    - 5.11.19
    - 5.11.20
    - 5.12.0
    - 5.12.1
    - 5.12.2
    - 5.12.3
    - 5.12.5
  - dependency-name: vuetify
    versions:
    - 2.4.10
    - 2.4.6
    - 2.4.7
    - 2.4.8
    - 2.4.9
  - dependency-name: eslint
    versions:
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: socket.io-client
    versions:
    - 3.1.1
    - 3.1.3
    - 4.0.0
  - dependency-name: "@nuxt/http"
    versions:
    - 0.6.3
  - dependency-name: nuxt
    versions:
    - 2.15.1
  - dependency-name: "@nuxt/types"
    versions:
    - 2.15.1
  - dependency-name: "@nuxt/content"
    versions:
    - 1.13.0
